/* tslint:disable */
/* eslint-disable */
/**
 * Docpad WebService API on local
 * Docpad Backend on local, deployment date: 2024-07-04
 *
 * The version of the OpenAPI document: v0.10.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

