# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new internal build to TestFlight"
  lane :internal do
    ENV['ENVFILE'] = '.env.development'
    ENV['FASTLANE_ITC_TEAM_ID']="DMVLDGZ8GW"

    ensure_git_status_clean

    increment_build_number(xcodeproj: "docpad.xcodeproj")

    match(type: "appstore")

    build_app(
      workspace: "docpad.xcworkspace",
      scheme: "docpad",
      xcargs: "-allowProvisioningUpdates",
      clean: true
    )

    changelog_from_git_commits

    api_key = app_store_connect_api_key(
      key_id: "UUY759MFJH",
      issuer_id: "69a6de7f-4d51-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_UUY759MFJH.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(skip_waiting_for_build_processing: false, api_key: api_key)

    clean_build_artifacts

    commit_version_bump(
      message: "Fastlane iOS: Released new build #{lane_context[SharedValues::BUILD_NUMBER]}", 
      xcodeproj: "docpad.xcodeproj",
      force: true
    )
  end
end
